sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
  slack: EcOlliVOlwu4fDz1qRIOzGRcHhnvBlSSgJwC3TFHI1ANL2ynSqEoaHVUv/OKpfbSWpzjr3KHxpnwa1YanJLH/BUHxF2HbbIeVm2LaLHqY/z+/xWrXyTK9ccUbeYT+kvMJeP1SP6GWOM4WdU5jL7qFbGiRuqFHHFY+8J/FcP8UvI191ky5YmUkFZMW2yzJeLr1jm6iHWEx4sDXfXMGe4PaPX0DbVnnvR5IXgxbTMB8dBmDNW+edAQZP27+xwwURLMInlC+QEZj3JTGB5jW6tspUzkq9oLA0rLXWvxeCJ/Cp0Hlg29JnsIZG8Fgh6QOcye+CizzzTxEBGZhzMFOE5Nj1+XFaZtJ0BW937JrlvOo6dJRVgcneBmvzstWPxi7EwPPc5vUuBIHrYsVbAWNd+W+1LqBcTp8kQpr1QGP+wnQLITvFIjIAmMuZlgOMxCBIBcVV2OQB44TqXt9Osp9pwym0j2vXaVP3kbvpde+cpQxrq70BTCNPXipLnrUH7vKnNaJ5UwBw7VaGtJfBBJ3BBEio1bMbRTPbBKjSdufBMcYRDGUDk6YBVAVSSCaatMWPFgJUEXpVNp2mA03AYtvwV5umJ4OoOaDnwBglleN7Lclm0r2LswFn/XY+/cdhhErAQQJtnT94sp3i1Z4JdtrMjPcsOhKsieIcQYY9bBP12OU+E=
node_js:
  - '5'
before_install:
  - npm i -g npm@^3.0.0
  - npm set progress=false
script:
  - npm test
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
