sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5'
before_install:
  - npm i -g npm@^3.0.0
  - npm set progress=false
script:
  - npm test
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
